# Generated by Selenium IDE
# import pytest
import time
import json
import unittest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestT031513(unittest.TestCase):
    def setUp(self):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def tearDown(self):
        self.driver.quit()

    def wait_for_window(self, timeout=2):
        time.sleep(round(timeout / 1000))
        wh_now = self.driver.window_handles
        wh_then = self.vars["window_handles"]
        if len(wh_now) > len(wh_then):
            return set(wh_now).difference(set(wh_then)).pop()

    def test_t031513(self):
        self.driver.get("https://www.baidu.com/")
        self.driver.set_window_size(866, 878)
        self.driver.find_element(By.ID, "kw").send_keys("杨幂")
        self.driver.find_element(By.ID, "su").click()
        time.sleep(8)
        self.vars["window_handles"] = self.driver.window_handles
        self.driver.find_element(By.LINK_TEXT, "杨幂_百度百科").click()
        self.vars["win4507"] = self.wait_for_window(2000)
        self.driver.switch_to.window(self.vars["win4507"])
        self.driver.execute_script("window.scrollTo(0,201)")
        self.vars["window_handles"] = self.driver.window_handles
        self.driver.find_element(By.CSS_SELECTOR, "#slider_works li:nth-child(3) img").click()
        self.vars["win9780"] = self.wait_for_window(2000)
        self.driver.switch_to.window(self.vars["win9780"])
        time.sleep(8)


if __name__ == "__main__":
    unittest.main()
